# Generated by Django 5.1.1 on 2024-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_game', '0002_playerscore_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='level',
            field=models.CharField(max_length=10),
        ),
    ]
