# Generated by Django 5.1.1 on 2024-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_game', '0004_remove_playerscore_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='level',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
