# Generated by Django 5.1.1 on 2024-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_game', '0007_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
